Fix TypeError
Test in python 3.6.0 request failed and rise：

```shell
TypeError: string argument expected, got 'bytes'
```

[reference to stackoverflow](https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in)